apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.userService.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.userService.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.userService.name }}
                port:
                  number: {{ .Values.userService.port }}