apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  jwt-private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDF6Xp6KX7zUhBu
    3yw+uoQxSKS/xg2eB3YkqYF5YgjBt6RoCfHk+5If8EF2v51kyCIqb/7Tu/YYNEnO
    oQ48GwU0PN1Sbsirv7waJ7ChZIdAQlh/uCqy9vr8IwSM6BgOB3z+47MbsO+g4iA6
    4OlhEy35CG42HMuS6mMRbSJ/BrEESP3EgkKd8mfFYEXsqbN18C8Q12qT5+yT0Buh
    rq1Istr8uh69fGNhsex0vI+1id6FtyA6NSpFSRvpRoaCGCZb3ca7mahN8XchdMZv
    knxLu+Anq65usTlvWrDNnUpeqkhUu0dvLq/u6avHBrlMDzpuoKXhkgv7eUvKZdaE
    7k4pyz7RAgMBAAECggEAExDagTFFLxidR6kNQJ/EQ2EtqeHhBvPOEFsaA4ELuenA
    l1s55+bKXXROQivUdFSJYhA2+tvVKeDDqXm/fs/VkQI6CgptH4qRiu1+6RVfqDOc
    BfXOez4q0KZo9lAXnSZghseVxhmmBBg0padsJDNuTtrejyz3+ZfF4nRiid0xqWlZ
    VKhHPO0dxorPDHU+Y172jojTiIzRFJbCh9GuScR0kPUwLTzFUwQMpx/hBTM/rC4b
    HNsdrjrk+iVaG2bUM7v0ME77j+ZKI+oDLIX5ChXgxUNSHCuGAZ8Rd4t6dUGJORUq
    0BuIp5AFuER2HgtDWtgQqeenVD/tfXZDIKUNnLwD7wKBgQDlde2GPRWraouucxPd
    rk6h93nkm+5B7PhC9aIn5tcQvyJDpHJCt73L5ipB2NpOqZtUFruMJhDHqbRIIjpw
    gK5rwv0ylSUGmz76/1QMa+QmUKGnDnSzBoJOP/tMtzulA5OE24RPPZ41uOHIEPMq
    TTMhcCPqvKb8sSJ3HqNAvJxUQwKBgQDczW5cg7gc2kotY/YaMzDUoDuaJXS5fwLc
    7SkVMB3UR55WjJ+077i83M7BYVPohV1z/Rt74qiT8pkGcs35OWRa0Y50rCIi3dQH
    oWw2k+EZLtecy7lN8MeN0Dwx5ALctTt4fAMQ3q5d20orieto0zbBxfCQOrILFXYy
    LAnhn3pZWwKBgG5XbjgeSbxbiP4DsqrodkGmuwP3A/TJ2nyAmFCtzf/smbKDcrqo
    lullLi7p89jd8KbYI6n6aBlLfzks1INjLfz+EDnxxJNPtlKG08kBXP4byhCGgBHS
    8HhmhhbXCiSI+rhpw09Dpz/YPyKxG+3cn9jVj0ADJh3fpF456nFoAZj3AoGAPtBi
    WQdP1UV0XL1XQdTWS2baDdwh/LNZSShey5xIoB9PuCeBN6QK1g+q8fCSQk/OajTT
    IMc2VgBp8B+w4Pmmxv9em2psu6aHrzQI6O3g150v0XdTXAzneDyJI1hOSCN2q6v7
    40y2JhVAYGp4AfY0WaPJ7/4CsIyGd3d3yCvqTokCgYEAjuI8lOfXfamZry8zTZdo
    BUq88fF8V+z352Usm6yMdFVNlcGAnLUwfJ4qj9MFhtzUOulHWfvDJkS4gG4pInt7
    3cPnDiZEpPfz6yz628NsglVwzhtKFnDx28WTByRfABaH+Z7IVYLcWRf5PFfhGSa+
    q2tQ+xJl014eAAp9swGLv38=
    -----END PRIVATE KEY-----

  jwt-public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxel6eil+81IQbt8sPrqE
    MUikv8YNngd2JKmBeWIIwbekaAnx5PuSH/BBdr+dZMgiKm/+07v2GDRJzqEOPBsF
    NDzdUm7Iq7+8GiewoWSHQEJYf7gqsvb6/CMEjOgYDgd8/uOzG7DvoOIgOuDpYRMt
    +QhuNhzLkupjEW0ifwaxBEj9xIJCnfJnxWBF7KmzdfAvENdqk+fsk9Aboa6tSLLa
    /LoevXxjYbHsdLyPtYnehbcgOjUqRUkb6UaGghgmW93Gu5moTfF3IXTGb5J8S7vg
    J6uubrE5b1qwzZ1KXqpIVLtHby6v7umrxwa5TA86bqCl4ZIL+3lLymXWhO5OKcs+
    0QIDAQAB
    -----END PUBLIC KEY-----
