apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.userService.name }}
spec:
  selector:
    app: {{ .Values.userService.name }}
  ports:
    - port: {{ .Values.userService.port }}
      targetPort: {{ .Values.userService.port }}
      nodePort: 30081
  type: NodePort