apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.user }}
  password: {{ .Values.rabbitmq.password }}
  vhost: {{ .Values.rabbitmq.vhost }}