apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.userService.db.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.userService.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.userService.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.userService.db.name }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.userService.db.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-user-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-user-secret
                  key: password
          resources:
            requests:
              cpu: {{ .Values.userService.db.resources.requests.cpu }}
              memory: {{ .Values.userService.db.resources.requests.memory }}
            limits:
              cpu: {{ .Values.userService.db.resources.limits.cpu }}
              memory: {{ .Values.userService.db.resources.limits.memory }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.userService.db.username }}
                - -d
                - {{ .Values.userService.db.database }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.userService.db.username }}
                - -d
                - {{ .Values.userService.db.database }}
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - name: postgres-user-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-user-data
          persistentVolumeClaim:
            claimName: postgres-user-pvc