apiVersion: v1
kind: Secret
metadata:
  name: postgres-user-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  username: {{ .Values.userService.db.username }}
  password: {{ .Values.userService.db.password }}
  database: {{ .Values.userService.db.database }}
  url: jdbc:postgresql://{{ .Values.userService.db.name }}:5432/{{ .Values.userService.db.database }}